version: '3.8'

services:
  auth-service:
    container_name: auth-service
    image: auth-service:0.0.1
    ports:
      - 3001:3001
    env_file:
      - .env
    restart: always
  config-service:
    container_name: config-service
    image: config-service:0.0.1
    ports:
      - 3003:3003
    env_file:
      - .env
    restart: always
  notify-service:
    container_name: notify-service
    image: notify-service:0.0.1
    ports:
      - 3002:3002
    env_file:
      - .env
    restart: always
  chat-service:
    container_name: chat-service
    image: chat-service:0.0.1
    ports:
      - 3004:3004
    env_file:
      - .env
    restart: always
  post-service:
    container_name: post-service
    image: post-service:0.0.1
    ports:
      - 3005:3005
    env_file:
      - .env
    restart: always
  point-service:
    container_name: point-service
    image: point-service:0.0.1
    ports:
      - 3006:3006
    env_file:
      - .env
    restart: always
  report-service:
    container_name: report-service
    image: report-service:0.0.1
    ports:
      - 3007:3007
    env_file:
      - .env
    restart: always

  booking-service:
    container_name: booking-service
    image: booking-service:0.0.1
    ports:
      - 3008:3008
    env_file:
      - .env
    restart: always

  cron-service:
    container_name: cron-service
    image: cron-service:0.0.1
    ports:
      - 3010:3010
    env_file:
      - .env
    restart: always

  admin-gateway:
    container_name: admin-gateway
    image: admin-gateway:0.0.1
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: always

  user-gateway:
    container_name: user-gateway
    image: user-gateway:0.0.1
    ports:
      - 3030:3030
    env_file:
      - .env
    restart: always
  socket-gateway:
    container_name: socket-gateway
    image: socket-gateway:0.0.1
    ports:
      - 3060:3060
    env_file:
      - .env
    restart: always

networks:
  gtrip-networks:
    driver: bridge
