export const errorMessage = {
  NOT_FOUND_ACCOUNT: 'NOT_FOUND_ACCOUNT',
  NOT_FOUND: 'NOT_FOUND',

  OTP_NOT_NOT_CORRECT: 'OTP_NOT_NOT_CORRECT',

  BAD_REQUEST: 'BAD_REQUEST',
  FORBIDDEN: 'FORBIDDEN',

  UN_AUTHORIZED: 'UN_AUTHORIZED',
  UN_ACTIVE: 'UN_ACTIVE',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_NOT_REGISTERED: 'EMAIL_NOT_REGISTERED',
  OTP_NOT_ALLOWED: 'OTP_NOT_ALLOWED',
  ACCOUNT_EXPIRED: 'ACCOUNT_EXPIRED',
  PASSWORD_NOT_MATCH: 'PASSWORD_NOT_MATCH',
  ACCOUNT_IS_DELETED: 'ACCOUNT_IS_DELETED',
  ROLE_NOT_VALID: 'ROLE NOT VALID',

  LANGUAGE_NOT_SUPPORTED: 'LANGUAGE_NOT_SUPPORTED',
  LANGUAGE_NOT_VALID: 'LANGUAGE_NOT_VALID',
  MISSING_LANG_CODE: 'MISSING_LANG_CODE',
  MISSING_CURRENCY_INFO: 'MISSING_CURRENCY_INFO',
  INVALID_CURRENCY_INFO: 'INVALID_CURRENCY_INFO',
  EMAIL_AND_OTP_NOT_MATCH: 'EMAIL_AND_OTP_NOT_MATCH',
  RATING_NOT_VALID: 'RATING_NOT_VALID',
  MAX_INTRODUCTION_IMAGE: 'MAX_INTRODUCTION_IMAGE',
  MAX_INTRODUCTION_BANNER: 'MAX_INTRODUCTION_BANNER',
  CURRENCY_CANT_BE_DELETED: 'CURRENCY_CANT_BE_DELETED',

  CANNOT_UPDATED: 'CANNOT_UPDATED',
  REQUEST_IS_SUCCESS: 'REQUEST_IS_SUCCESS',

  // booking
  MINIMUM_WORKING_TIME: 'MINIMUM_WORKING_TIME',
  BOOKING_TIME_NOT_VALID: 'BOOKING_TIME_NOT_VALID',
  BABY_SITTER_NOT_ALLOW_BOOKING: 'BABY_SITTER_NOT_ALLOW_BOOKING',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_NOT_PENDING: 'BOOKING_NOT_PENDING',
  BOOKING_CANT_BE_CANCEL: 'BOOKING_CANT_BE_CANCEL',
};
